version: "3.8"

services:
  frontend:
    build:
      context: ./department-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./department-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
